# Generated by Django 2.2 on 2019-04-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_auto_20190421_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartments',
            name='Size',
        ),
        migrations.AddField(
            model_name='apartments',
            name='Description',
            field=models.CharField(default='None', max_length=250),
        ),
    ]
