# Generated by Django 2.2 on 2019-04-21 19:05

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_auto_20190421_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantdecision',
            name='Country_of_choice',
            field=django_countries.fields.CountryField(default='', max_length=2),
        ),
    ]
