# Generated by Django 2.2 on 2019-04-22 14:11

from django.db import migrations, models
import django_countries.fields
import multipleselectionfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddBeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_beds', models.CharField(default='None', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'beds',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('Unit', models.CharField(max_length=200)),
                ('Type', multipleselectionfield.db.fields.MultipleSelectionField(choices=[(1, 'flat'), (2, 'bungalow'), (3, 'self-contain'), (4, 'studio apartment'), (5, 'single-room')], max_length=9, null=True)),
                ('beds', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 'others')], max_length=100)),
                ('Baths', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 'others')], max_length=100)),
                ('SQFT', models.CharField(default='None', max_length=50)),
                ('Country', django_countries.fields.CountryField(default='', max_length=2)),
                ('Photo', models.ImageField(height_field=300, upload_to='', width_field=300)),
                ('Available_from', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'properties',
            },
        ),
    ]
